### ISSUE TITLE
h!uhc not working.

### ISSUE THREAD

**Issue by AsksTooManyQuestions** [HyDiscord/HyDiscord#2]
h!uhc currently not working.

**Comment by AsksTooManyQuestions** [comment]
![image](https://user-images.githubusercontent.com/79485154/111215600-b0f8e180-85a9-11eb-9914-b0314f6aac1d.png)

**Comment by ghost** [comment]
Hey, sorry for replying late but I will try to fix it. I have so many
things going on and I haven't had time to work on HyDiscord.

**Comment by ghost** [comment]
Should be fixed in the next commit.
